blueprint:
  name: Z-Wave JS - Vesternet Wall Controller 2-Button 
  description:
    "Create automations for Vesternet 2-Button Scene Controller [VES-ZW-WAL-003](https://www.vesternet.com/en-global/collections/z-wave-keyfobs-remotes-wall-controllers/products/vesternet-z-wave-wall-controller) using the Z-Wave JS integration.
    
    The buttons are labelled assuming the LED is positioned at the top of the device.

    The automations supports the following triggers for each button:

    * Pressed
 
    * Held Down
 
    * Released
 
    "
  domain: automation
  input:
    vesternet_device:
      name: Vesternet Controller
      description: List of available Vesternet 4-Button devices.
      selector:
        device:
          integration: zwave_js
          manufacturer: Vesternet
          model: VES-ZW-WAL-003
    I1_key_pressed:
      name: ON (I) Key Pressed
      description: Action to run when ON (I) button is pressed
      default: []
      selector:
        action: {}
    O1_key_pressed:
      name: OFF (O) Key Pressed
      description: Action to run when OFF (O) button is pressed
      default: []
      selector:
        action: {}
    
    I1_key_held_down:
      name: ON (I) Held Down
      description: Action to run when ON (I) button is held down
      default: []
      selector:
        action: {}
    I1_key_released:
      name: ON (I) Released
      description: Action to run when ON (I) button is released after being held down.
      default: []
      selector:
        action: {}

    O1_key_held_down:
      name: OFF (O) Held Down
      description: Action to run when OFF (O) button is held down
      default: []
      selector:
        action: {}
    O1_key_released:
      name: OFF (O) Released
      description: Action to run when OFF (O) button is released after being held down.
      default: []
      selector:
        action: {}
    
  source_url: https://github.com/beerygaz/ha-bp-VES-ZW-WAL-003
mode: single
max_exceeded: silent
variables:
  device_id: !input "vesternet_device"
trigger:
  - platform: event
    event_type: zwave_js_value_notification
condition: "{{ trigger.event.data.device_id == device_id }}"
action:
  - variables:
      property_key_name: "{{ trigger.event.data.property_key_name }}"
      property_name: "{{ trigger.event.data.property_name }}"
      label: "{{ trigger.event.data.label }}"
      command_class_name: "{{ trigger.event.data.command_class_name }}"
      value: "{{ trigger.event.data.value }}"
      node_id: "{{ trigger.event.data.node_id }}"
  - service: logbook.log
    data:
      name: Z-Wave JS
      message:
        "received event from node {{node_id}}: {{ command_class_name }} - {{
        value }} - {{ label }}"
  - choose:
      - conditions:
          "{{  property_name == 'scene' \n    and property_key_name == '001'\n\
          \    and value == 'KeyPressed' }}\n"
        sequence: !input "I1_key_pressed"
      - conditions:
          "{{  property_name == 'scene' \n    and property_key_name == '002'\n\
          \    and value == 'KeyPressed' }}\n"
        sequence: !input "O1_key_pressed"
      
      - conditions:
          "{{  property_name == 'scene' \n    and property_key_name == '001'\n\
          \    and value == 'KeyHeldDown' \n}}\n"
        sequence: !input "I1_key_held_down"
      - conditions:
          "{{  property_name == 'scene' \n    and property_key_name == '001'\n\
          \    and value == 'KeyReleased' \n}}\n"
        sequence: !input "I1_key_released"

      - conditions:
          "{{  property_name == 'scene' \n    and property_key_name == '002'\n\
          \    and value == 'KeyHeldDown' \n}}\n"
        sequence: !input "O1_key_held_down"
      - conditions:
          "{{  property_name == 'scene' \n    and property_key_name == '002'\n\
          \    and value == 'KeyReleased' \n}}\n"
        sequence: !input "O1_key_released"

      